### ISSUE TITLE
Additions to the BOM for motor power

### ISSUE THREAD

**Issue by cactus314** [ISS-Mimic/Mimic#238]
Not sure which section of the BOM these should go in, but they are required for supplying power to the motor shields (and thus the BGAs and SARGs).  It's not quite the same setup as what Bryan put together - I think it's a little cleaner by using a splitter.

1. [LEDO 12V/5A Power Supply](https://smile.amazon.com/gp/product/B01461MOGQ/ref=ppx_yo_dt_b_asin_title_o06_s01?ie=UTF8&psc=1) (Amazon)
2. [JEEUE 12V Power DC Male to Female Cable with On/Off Switch](https://smile.amazon.com/gp/product/B08SJQ8BXD/ref=ppx_yo_dt_b_asin_title_o06_s00?ie=UTF8&psc=1) (Amazon) - optional
3. [DZYDZR 3pcs 5.5mm x 2.1mm Y Splitter Cable 1 Female to 3 Male Splitter](https://smile.amazon.com/gp/product/B06Y5G3CMJ/ref=ppx_yo_dt_b_asin_title_o06_s00?ie=UTF8&psc=1) (Amazon) - package of 3, one required.
4. [DC Power Plug Pigtail Cable (Female Power Plug Pigtail Cable / 19.68 inches/Pack of 10)](https://smile.amazon.com/gp/product/B01M0EAR9N/ref=ppx_yo_dt_b_asin_title_o06_s00?ie=UTF8&psc=1) (Amazon) - only three of the pigtails will be used. 

EDITED: Changed line item 4 to longer pigtails

**Comment by juggler2000** [comment]
1. Suggested unit is fine, but this is what we'd been using due to some good history with prior products from the manufacturer. https://smile.amazon.com/gp/product/B075FPQ2YQ/
2. Previously used this four-pack.  This was so there was a master power switch to all motors, then individuals for each motor.  Can simplify down to just the one, but the multiples had helped with some debugging in the past (can always just unplug the barrel jack instead). https://smile.amazon.com/gp/product/B082Y37QRV/ 
3. Great.
4. Great.
